### ISSUE TITLE
Ugly output when URLs are 404

### ISSUE THREAD

**Issue by nyetsche** [NCBI-Hackathons/Code_in_PubMed_Abstracts#1]
I.e., like this:

``````
Processed 220 of 2499Unable to connect to URL: //github.com/SuLab/crowd_cid_relexDatabase result 404
Processed 310 of 2499Unable to connect to URL: atwww.github.com/BrunildaBalliu/TrioEpi result 404```

Or maybe it's a parsing error?
``````

**Comment by nyetsche** [comment]
The second one smells like a parsing error: `http[s]://www.github.com/BrunildaBalliu/TrioEpi` exists.

`http[s]://github.com/SuLab/crowd_cid_relexDatabase` is indeed 404.

**Comment by johnbradley** [comment]
See this link: http://www.ncbi.nlm.nih.gov/pubmed/26865367

```
The method is publicly available atwww.github.com/BrunildaBalliu/TrioEpi.
```

I couldn't come up with a safe way to remove the bogus "at" in the original text.

**Comment by nyetsche** [comment]
Yes, I see now. GIGO. I suppose some heuristics might get around that, but with only 26 out of 2499 abstracts having problems it's not so bad to hand check. I edited `is_url_valid` to include the PMID.

**Comment by nyetsche** [comment]
Commits 281e628 and previous make the output cleaner, which solves the immediate bug. Not yet sure if it's worth adding checking on URLs if humans can look up the PMID and spot the mistakes.

```
PMID: 27087308. Unable to connect to URL: http://github.com/SuLab/crowd_cid_relexDatabase result 404
PMID: 26865367. Unable to connect to URL: http://atwww.github.com/BrunildaBalliu/TrioEpi result 404
[...]
```
